# Generated by Django 4.2.6 on 2023-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
    ]
